/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CadastroController;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.Cadastro;

/**
 *
 * @author mathe
 */
public class SignupScreen extends javax.swing.JFrame {

    /**
     * Creates new form SignupScreen
     */
    public SignupScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pane = new javax.swing.JPanel();
        bCadastrar = new javax.swing.JButton();
        lNome = new javax.swing.JLabel();
        lLogin = new javax.swing.JLabel();
        lSenha1 = new javax.swing.JLabel();
        lsenha2 = new javax.swing.JLabel();
        pSenha2 = new javax.swing.JPasswordField();
        pSenha1 = new javax.swing.JPasswordField();
        textLogin = new javax.swing.JTextField();
        textNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bCadastrar.setText("Cadastrar");
        bCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCadastrarMouseClicked(evt);
            }
        });

        lNome.setText("Nome");

        lLogin.setText("Login");

        lSenha1.setText("Senha");

        lsenha2.setText("Confirme a senha");

        textLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PaneLayout = new javax.swing.GroupLayout(Pane);
        Pane.setLayout(PaneLayout);
        PaneLayout.setHorizontalGroup(
            PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lSenha1)
                    .addComponent(lsenha2)
                    .addComponent(lLogin)
                    .addComponent(lNome))
                .addGap(18, 18, 18)
                .addGroup(PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(textNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(textLogin)
                        .addComponent(pSenha2)
                        .addComponent(pSenha1)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        PaneLayout.setVerticalGroup(
            PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lNome)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lLogin)
                    .addComponent(textLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSenha1)
                    .addComponent(pSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lsenha2)
                    .addComponent(pSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCadastrar)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLoginActionPerformed

    private void bCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCadastrarMouseClicked
        Cadastro c = new Cadastro();
        boolean check = true;
        String msgVazio = "Campos Vazios:\n";
        String msgLogin = "";
        String msgSenha = "";
        lNome.setForeground(Color.BLACK);
        lLogin.setForeground(Color.BLACK);
        lSenha1.setForeground(Color.BLACK);
        lsenha2.setForeground(Color.BLACK);

        if (textNome.getText().equals("")) {
            check = false;

            msgVazio = msgVazio + "Nome;\n";
            lNome.setForeground(Color.red);
        }
        if (textLogin.getText().length() < 2) {
            check = false;
            msgLogin = "Tamanho mínimo Login: 3 Caracteres\n";
            lLogin.setForeground(Color.red);
        }
        if (textLogin.getText().equals("")) {
            check = false;

            msgVazio = msgVazio + "Login;\n";
            lLogin.setForeground(Color.red);
        }
        if (pSenha1.getText().length() < 2) {
            msgSenha = "Tamanho mínimo Senha: 3 Caracteres\n";
            lSenha1.setForeground(Color.red);
            if (pSenha1.getText().equals("")) {
                check = false;

                msgVazio = msgVazio + "senha;\n";
                lSenha1.setForeground(Color.red);
            }
        }

        if (pSenha2.getText().equals("")) {
            check = false;

            msgVazio = msgVazio + "Confirmação de senha;\n ";
            lsenha2.setForeground(Color.red);
        }
        if (!(pSenha1.getText().equals(pSenha2.getText()))) {
            check = false;
            JOptionPane.showMessageDialog(null, "Senhas não batem!");
            lsenha2.setForeground(Color.red);
        }
        if (check == false) {
            JOptionPane.showMessageDialog(null, msgLogin + msgSenha + msgVazio);

        } else {
            c.setLogin(textLogin.getText());
            c.setNome(textNome.getText());
            c.setSenha(pSenha1.getText());
            CadastroController cc = new CadastroController();
            cc.save(c);
            JOptionPane.showMessageDialog(null, "Cadastro Efetuado!");
            this.dispose();
        }

    }//GEN-LAST:event_bCadastrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pane;
    private javax.swing.JButton bCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lSenha1;
    private javax.swing.JLabel lsenha2;
    private javax.swing.JPasswordField pSenha1;
    private javax.swing.JPasswordField pSenha2;
    private javax.swing.JTextField textLogin;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables
}
